print('Welcome to the Mad Lib Generator!')

adjective=raw_input('Type in an adjective:')
adjective2 = raw_input('Another adjective:')
adjective3 = raw_input('And anotehr adjective:')
adjective4 = raw_input('One more adjective:')
animal = raw_input('Plural animal (e.g. puppies):')
verb = raw_input('Now a verb:')
noun = raw_input('Now a plural noun:')
musician = raw_input('The first name of a female musician:')
beverage = raw_input('A beverage:')
body_part = raw_input('And finally, a plural body part:')

print('')
print("Excellent choices! Here's your story.... " )
print('-------------------------------------------')
print('There once was a '+ adjective + ' programmer named ' + musician) 
print('who wanted to build a ' + adjective2 + ' mobile app to help ' + adjective3) 
print(animal + ' find new homes.')
print('')
print(musician + ' stayed up all night, drinking lots of caffeinated ' + beverage)
print('as she worked and worked trying to complete her fancy program.')
print('')
print('Whenver ' + musician + ' hit a dead end, she would exclaim *' + noun + '*!')
print('')
print('But she was not discouraged, and after a quick break to ')
print(verb + ' and clear her head, she got back to work.')
print('')
print('By morning, when the sun started to rise, she let out a big yawn')
print('and stretched her ' + body_part + '. Finally, she was done.')
print('-------------------------------------------')